### ISSUE TITLE
convertir a rst la primer versión de la constitución

### ISSUE THREAD

**Issue by ceyusa** [ceyusa/constitucion-mexicana#4]
La primer versión de la constitución, publicada el 5 de febrero de 1917, está disponible digitalizada en formato PDF aquí:

http://www.diputados.gob.mx/LeyesBiblio/ref/dof/CPEUM_orig_05feb1917.pdf

Habría que convertirla a rst y propongo dividirla en archivos: uno por cada artículo, y otros archivos que conformen los títulos y capitulos. Los transitorios también serían un archivo distinto.

**Comment by esbeto** [comment]
Se podrían hacer carpetas por cada capítulo / título / sección. Sólo tendríamos que entender primero cómo está organizada jerárquicamente

Los transitorios son una locura, y por alguna razón seguimos guardando esos artículos. (Que según escuché en una [plática de Pedro Salazar](https://www.youtube.com/watch?v=LlZ7G9dzoRw) pueden llegar a ser del mismo tamaño o más grandes que el texto constitucional)

**Comment by ceyusa** [comment]
He empujado la rama [02051917](https://github.com/ceyusa/constitucion-mexicana/tree/02051917) (bien original el nombre) con un makefile que descarga la versión PDF de la Constitución original del 17, la convierte a texto plano, la divide en 138 archivos rst y aplica un formato con ancho máximo de 72 caracteres.

También incluye un archivo ``toc.rst`` que es la el esqueleto, contiene los títulos, capítulos y secciones. 

Un tercer commit es un WIP con el primer capítulo formateado.

Si me pueden echar la mano con otros capítulos, se los agradecería mucho. Solo respeten los 72 caracteres y el formato rst.

**Comment by ceyusa** [comment]
Terminada esta tarea! \o/

La rama ahora se llama V2 y está rebaseada al origen del repositorio. Y como plus, también esta el primer cambio constitucional como commit :)
